mode: dev

Server:
  RunMode: debug
  HttpPort: 8080

Database:
  DBType: postgres
  Username: user
  Password: password
  Host: 127.0.0.1:5431
  DBName: the_message
  Charset: utf8
  MaxIdleConns: 10
  MaxOpenConns: 30