mode: dev

Server:
  RunMode: debug
  HttpPort: 8080

Database:
  DBType: mysql
  Username: user
  Password: test
  Host: 127.0.0.1:3306
  DBName: test_app
  TablePrefix: test_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30