version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB:  the_message
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: UTC
    ports:
      - 5431:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: pg_isready -U user -d the_message
      interval: 5s
      timeout: 2s
      retries: 5